# ____________________________________________________________________________78

#+TITLE: Initialization files setup in Emacs
#+DESCRIPTION: 
#+AUTHOR: cissic
#+DATE: <2022-12-27 Tue>
#+TAGS: emacs packages
#+OPTIONS: toc:nil
#+OPTIONS: -:nil


* {{{title}}
:PROPERTIES:
:PRJ-DIR: ~/.emacs.d/     
:END:
# :PROPERTIES:
# :PRJ-DIR: ./2022-12-27-init-and-setup-Emacs/
# :END:


** TL;DR
An org source of this post can be found
[[https://github.com/cissic/cissic.github.io/blob/main/mysource/public-notes-org/2022-12-27-configuring-and-installing-emacs.org][here]]. This org-file can be used to generate (tangle in Emacs nomenclature)
to scripts:
~install-packages.el~ and
~init.el~.
Place them in your ~./emacs.d~ and hope ;) they will run without
problems on your machine.


** Problem description
The aim of this post is to finally have clean and tidy Emacs initialization file.
After some time of battling with Emacs with the use of 
find-and-copy-snippets-from-internet I decided I had achieved sufficient level of 
experience to rewrite init.el from the scratch.
In the post I'm going to implement the following rules:

1. Installation/Updating of packages is perfomed in separate file 
   ~install-packages.el~ (abbreviation for =install or upgrage packages=) which is intended to be executed every now and then,
   while Emacs initialization is done in ~init.el~.
2. I'm not going to use ~use-package~ since I still don't get it well. What is
    more, according to [[https://emacs.stackexchange.com/questions/44266/require-vs-package-initialize][this post]] ~use-package~ is just 
   a fancier way of doing things that can be done in vanilla Emacs.
   # it's still a bit to complicated for me.
3. The style of init.el presented on [[https://docs.freebsd.org/en/books/developers-handbook/tools/#emacs][this page]] is something that seems to 
   look nice and I'm going to implement this approach.
4. I'm not going to use multi-init-files approach presented ... somewhere 
   I saw some time ago and I'm unable to locate it now... 
   As for now I think all-setup-in-one-file approach means less clutter.
5. I want to do things in emacsian way. So most of the comments are going to be
   included in this org file. ~install-packages.el~ and ~init.el~ will be tangled
   from it: ~C-c C-v t~. If this shortcut does not work (for plain emacs 27.1
   installation tangling didn't work out of the box so I needed to load 
   ~ox~ package: 
   -> ~M-x eval-expression~ 
   -> ~(require 'ox)~ )

   There is an optional way of approaching this point presented 
   [[http://gewhere.github.io/orgmode-emacs-init-file][here]]. It comes down to extracting ~emacs-lisp~ source snippets directly
   from an .org file when evaluating ~init.el~. I have no idea whether there are
   any relevant differences between both approaches.


*** Sources worth further reading
- https://ruzkuku.com/emacs.d.html#org804158b - with a list of other useful
  pages with configurations
 
- https://docs.freebsd.org/en/books/developers-handbook/tools/#emacs

- https://karthinks.com/software/batteries-included-with-emacs/
- https://karthinks.com/software/more-batteries-included-with-emacs/
 
- https://stackoverflow.com/questions/5500035/set-custom-keybinding-for-specific-emacs-mode
- https://tuhdo.github.io/emacs-tutor3.html
- https://karthinks.com



**** Latex (not interesting after getting used to org?)
https://karthinks.com/software/latex-input-for-impatient-scholars/


** Installation/upgrade script
This script is meant to (re-)install/prepare/upgrade Emacs packages in order
to have fully working Emacs environment.  

This is an installation (or upgrade) script to keep installation commands 
outside init.el, in order to have everything clean and tidy (for details and 
discussion [[https://stackoverflow.com/questions/55038594/setting-up-emacs-on-new-machine-with-init-el-and-package-installation][check this]]).
Each time this script is run, the packages are not only installed but also
upgraded. Thus, it might happen that a new version of some package
breaks your installation. In order to prevent this troublesome situation
it's better to keep whole .emacs.d directory as a git repository and
make a commit before executing this script. Then, in case any problems
you can go back to restore properly working emacs installation.

Before running this script you should have git repository initialized in emacs
directory.
The repository should contain the following content:
- init.el
- install-packages.el
- elpa/
- .gitignore
- ...

Synchronization of the local repository with the remote one is not
performed in this script. It should be performed explicitely by the user
in a convenient time.

*** Preparation

First, there is a configuration line. The user needs to set the directory where Emacs initialization files are located (I know in new Emacs there exist some 
variable for this but a bit of redundancy won't do much harm).

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el") :mkdirp yes :exports none

    ;; ____________________________________________________________________________78
    ;; install-mb-packages.el
    ;; The full description of what is done in this file is included in 
    ;; accompanying .org file (configuring-and-installing-emacs.org) that is
    ;; described here:
    ;; https://cissic.github.io/posts/configuring-and-installing-emacs/


    ;; Path to your Emacs directory:
    (setq my-emacs-dir "~/.emacs.d/")
    ;;;; (let (my-emacs-dir "~/.emacs.d/"))

#+end_src

Each time this script is run, the packages are not only installed but also
upgraded. Thus, it might happen that a new version of some package
breaks your installation. In order to prevent this troublesome situation
it's better to keep whole .emacs.d directory as a git repository and
make a commit before executing this script. Then, in case any problems
you can go back to restore properly working emacs installation.
Before running this script you should have a git repository initialized in emacs
directory and git itself installed in the system (see Sec. [[dependencies-section]]).
Synchronization of the local repository with the remote one is not
performed in this script. It should be performed explicitely by the user
in a convenient time.

In order to make a git commit from within elisp script I followed [[https://emacs.stackexchange.com/questions/48954/the-elisp-function-to-run-the-shell-command-in-specific-file-path][this post]].

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el") :mkdirp yes
;; Make a git commit of your repository.
;; 
(let ((default-directory my-emacs-dir)) ; run command `git add -u` in the context of my-emacs-dir
  (shell-command "git add -u"))
(let ((default-directory my-emacs-dir)) ; run command `git commmit` in the context of my-emacs-dir
  (shell-command
   "git commit -m 'Precautionary commit before running install-mb-packages.el'"))
#+end_src

Perform [[https://emacs.stackexchange.com/questions/44266/require-vs-package-initialize][package initialization]], only for Emacs < 27.1, since in Emacs 27.1
~package-initialize~ is executed automatically, before
loading the init file ([[https://www.masteringemacs.org/article/whats-new-in-emacs-27-1][see here]]).

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el") :mkdirp yes

(when (< emacs-major-version 27)
  (package-initialize)) ;  set up the load-paths and autoloads for installed packages
(setq package-check-signature nil)

#+end_src

# ____________________________________________________________________________78
then declare repositories where emacs packages can be found. It used to be more  
addresses here, something like:

#+begin_src emacs-lisp 

(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")  ;; default value of package-archives in Emacs 27.1
        ; ("marmalade" . "http://marmalade-repo.org/packages/")
        ("melpa" . "https://melpa.org/packages/")
	("melpa-stable" . "http://stable.melpa.org/packages/")
	; ("org" . "https://orgmode.org/elpa/")    ;;; removed as a way of dealing with https://emacs.stackexchange.com/questions/70081/how-to-deal-with-this-message-important-please-install-org-from-gnu-elpa-as-o
	))
#+end_src

but, at the time of writing this (Jan, 2023), the biggest, the freshest etc. 
repository is ~melpa~ and it is advised to work with it. ~Marmalade~ is 
outdated, and I also needed to get rid of ~orgmode~ as a remedy for 
[[https://emacs.stackexchange.com/questions/70081/how-to-deal-with-this-message-important-please-install-org-from-gnu-elpa-as-o][some problem]] ([[https://www.reddit.com/r/emacs/comments/9rj5ou/comment/e8iizni/?utm_source=share&utm_medium=web2x&context=3][BTW]]).
So now my list of repositories looks as follows: 

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")

;;first, declare repositories
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")  ;; default value of package-archives in Emacs 27.1
        ("melpa" . "https://melpa.org/packages/")
	("melpa-stable" . "http://stable.melpa.org/packages/")
	))

#+end_src

Now, synchronize your data: download descriptions of ELPA packages 
and update the cache with current versions of
packages kept in remote repositories:

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")
;; Refresh the repositories to have the newest versions of the packages
(package-refresh-contents)

#+end_src

In Emacs 27.1 it [[https://emacs.stackexchange.com/a/44287][shouldn't be necessary to use]]
~(require 'packagename)~, so I can leave out the following code:

# #+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")

#+begin_src emacs-lisp 
;; ;; Comment out if you've already loaded this package...
;; (require 'cl-lib)       ;; built-in in 27.1
;; (require 'package)      ;; built-in in 27.1
#+end_src


*** The main part of the installation script - list of the packages
I used to have ~(defvar my-packages ...~ instead of ~(setq my-packages ...~ 
below but... *Do not* use ~defvar~ for declaring a list of packages to be installed!
If the variable is already defined 
[[https://emacs.stackexchange.com/questions/29710/whats-the-difference-between-setq-and-defvar][~defvar~ does nothing]] with it so it does 
not refresh a list after editing it and thus it prevents from the 
expected way of reevaluating of the ~package-install.el~.


The main point of the file. Set the list of packages to be installed
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")
(setq my-packages
  '(
#+end_src

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")
    ; counsel ; for ivy
    company
    ;dockerfile-mode    
    ;flycheck
    ;flycheck-pos-tip
    flyspell
    ;; google-this
    ido
    ; ivy
    ; jedi
    magit
    markdown-mode
    ;matlab-mode 
    modus-themes ; theme by Protesilaos Stavrou
    ;moe-theme ; https://github.com/kuanyui/moe-theme.el
    ;mh
    ;ob-async
    org   ; ver. 9.3  built-in in Emacs 27.1; this install version 9.6 from melpa
    org-ac
    ;org-download
    ;org-mime
    ;org-ref
    org-special-block-extras
    ;ox-gfm
    ;ox-pandoc
    ; ox-ipynb -> manual-download
    ;pandoc-mode
    ;pdf-tools
    popup   ; for yasnippet
    ;projectile
    ;pyenv-mode
    ;Pylint  ; zeby dzialal interpreter python'a po:  C-c C-c 
    ;rebox2
    ;recentf
    ;session-async
    ;shell-pop
    smex
    ; tramp  ; ver. 2.4.2 built-in in Emacs 27.1
    ;tao-theme ; https://github.com/11111000000/tao-theme-emacs
    ;treemacs
    ;use-package
    workgroups2
    ;w3m
    yasnippet
    )
  ;; "A list of packages to be installed at Emacs launch."
  )

#+end_src

And finally, perform the installation/upgrade of packages and 
print an information message.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "install-packages.el")

(defun my-packages-installed-p ()
  (cl-loop for p in my-packages
           when (not (package-installed-p p)) do (cl-return nil)
           finally (cl-return t)))

(unless (my-packages-installed-p)
  ;; check for new packages (package versions)
  (package-refresh-contents)
  ;; install the missing packages
  (dolist (p my-packages)
    (when (not (package-installed-p p))
      (package-install p))))

;; ; (jedi:install-server)

(message "All done in install-packages.")


#+end_src


*** Problems/errors during installation of packages
No problems so far...


** My init.el

There's something like ~early-init.el~ in modern versions of Emacs that is intended
to speed up the launching process, however I'm not going to use this approach as
for now. An interesting discussion about this can be found [[https://www.reddit.com/r/emacs/comments/enmbv4/earlyinitel_reduce_init_time_about_02_sec_and/][here]].

*** A note:
[[https://stackoverflow.com/questions/12224575/emacs-init-el-file-doesnt-load][When Emacs ~init.el~ does not load at startup]].


#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :mkdirp yes :exports none
;; ____________________________________________________________________________78
;; init.el
;; The full description of what is done in this file is included in 
;; accompanying .org file (configuring-and-installing-emacs.org). 
#+end_src


**** [DEPRECATED] Setting an auxiliary variable
This section is deprecated in favour of [[workgroups2-and-sessions][~workgroups2 package~]].

#+begin_src emacs-lisp
;; This file is designed to be re-evaled; use the variable first-time
;; to avoid any problems with this.
(defvar first-time t
  "Flag signifying this is the first time that .emacs has been evaled")
#+end_src


**** Package ~package~  initialization
In theory, in new Emacs two following lines shouldn't be required to have 
everything working fine.
However, it seems that some packages (~modus-themes~, ~workgroups2~?) cannot 
run without it when emacs commands are to be executed from command line 
without invoking Emacs 
window (Post with demonstration makefile should be published soon).

 
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
(require 'package)
(package-initialize)
#+end_src

*** Setting separate file for emacs custom entries
If you don't set the separate for custom entries, Emacs appends its code
directly into ~init.el~. To prevent this we need to define other file. 
Remember to create ~custom-file.el~ file by hand! Emacs won't create it 
for you.

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
# ;;;; Do not use `init.el` for `custom-*` code - use `custom-file.el`.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
(setq custom-file "~/.emacs.d/custom-file.el")
#+end_src

Assuming that the code in custom-file is execute before the code
ahead of this line is not a safe assumption. So load this file
proactively.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
(load-file custom-file)
#+end_src



*** Global emacs customization

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Global emacs customization
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src

Here are global Emacs customization. 
If necessary some useful infomation or link is added to the customization.

**** Self-descriptive oneliners <<oneliners>>

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
  (auto-revert-mode 1)       ; Automatically reload file from a disk after change
  (global-auto-revert-mode 1) 

  (delete-selection-mode 1)  ; Replace selected text

  (show-paren-mode 1)        ; Highlight matching parenthesis

  (global-linum-mode 1)      ; Enable line numbering

  (scroll-bar-mode 1)        ; Enable scrollbar
  (menu-bar-mode 1)          ; Enable menubar
  (tool-bar-mode -1)         ; Disable toolbar since it's rather useless

  (setq line-number-mode t)  ; Show line number

  (setq column-number-mode t); Show column number

  (define-key global-map (kbd "RET") 'newline-and-indent) ; Auto-indent new lines

  (desktop-save-mode 1)      ; Save windows layout on closing
  (setq desktop-load-locked-desktop t) ; and don't ask for confirmation when 
			     ; opening locked desktop
  (setq desktop-save t)

  (save-place-mode t)        ; When re-entering a file, return to the place, 
			     ; where I was when I left it the last time.

#+end_src

**** Emacs shell history from previous sessions
[[https://www.emacswiki.org/emacs/SaveHist][Emacs wiki page]]

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(savehist-mode 1)          ; Save history for future sessions
#+end_src

**** Easily restore previous/next window layout 

- undo = previous window view
 : C-c left  
- redo (undo undo)
 : C-c right 
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(winner-mode 1)            ; Toggle between previous window layouts
#+end_src


**** Line truncation

There are some other ways of [[https://stackoverflow.com/questions/7577614/emacs-truncate-lines-in-all-buffers][truncating]]:
#+begin_example
(setq-default truncate-lines t) ; ugly way of truncating
#+end_example
or
#+begin_example
; fancier way of truncating (word truncating) THIS DOES NOT WORK!!!
(setq-default global-visual-line-mode t) 
#+end_example
however I didn't find them pretty and finally this command is useful:
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(global-visual-line-mode t) ; Truncate lines 
#+end_src


**** Prevent from deselecting text after M-w copying 
[[https://www.reddit.com/r/emacs/comments/1vdumz/emacs_to_keep_selection_after_copy/][Link]]

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; Do not deselect after M-w copying -> 
 (defadvice kill-ring-save (after keep-transient-mark-active ())
   "Override the deactivation of the mark."
   (setq deactivate-mark nil))
 (ad-activate 'kill-ring-save)
;; <- Do not deselect after M-w copying
#+end_src

**** Setting default font

To get the list of available fonts:
Type the following in the *scratch* buffer, and press ~C-j~ at the end of it:
   ~(font-family-list)~
You may need to expand the result to see all of them, by hitting enter on 
the =...= at the end.
([[https://stackoverflow.com/questions/13747749/font-families-for-emacs][Source]]).

The font of my choice is:
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")  
(set-frame-font "liberation mono 11" nil t) ; Set default font
#+end_src

**** Highlight on an active window/buffer
Although the active window can be recognized
by the cursor which blinking in it, sometimes it is hard to
find in on the screen (especially if you use a colourful theme
like [[modus-theme]].

I found a [[https://stackoverflow.com/questions/33195122/highlight-current-active-window][post]] adressing this issue.
Although the accepted answer is using 
~auto-dim-other-buffers.el~
I prefer [[https://stackoverflow.com/a/33196798][this solution]] which does not rely on external package
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;;Highlight an active window/buffer or dim all other windows
  
  (defun highlight-selected-window ()
    "Highlight selected window with a different background color."
    (walk-windows (lambda (w)
      (unless (eq w (selected-window)) 
	(with-current-buffer (window-buffer w)
	  (buffer-face-set '(:background "#111"))))))
    (buffer-face-set 'default))
  
    (add-hook 'buffer-list-update-hook 'highlight-selected-window)
;;
#+end_src


**** Time and calendar 

***** DONE Locale for names of days of the week in org-mode
# Setting default locale
Setting names of the days of the week and months to arbitrarily language:
[[https://emacs.stackexchange.com/questions/50543/insert-date-using-a-calendar-where-other-language-rather-than-english-is-desir][Link 1]],
[[https://emacs.stackexchange.com/questions/19602/org-calendar-change-date-language/19611#19611][Link 2]]
# ;; (setq calendar-week-start-day 1
# ;;           calendar-day-name-array ["Domenica" "Lunedì" "Martedì" "Mercoledì" 
# ;;                                    "Giovedì" "Venerdì" "Sabato"]
# ;;           calendar-month-name-array ["Gennaio" "Febbraio" "Marzo" "Aprile" "Maggio"
# ;;                                      "Giugno" "Luglio" "Agosto" "Settembre" 
# ;;                                      "Ottobre" "Novembre" "Dicembre"])
# ;; (setq calendar-week-start-day 1
# ;;       calendar-day-name-array["Sunday" "Monday" "Tuesday"
# ;; 			      "Wednesday" "Thursday" "Friday" "Saturday"]
# ;;       calendar-month-name-array ["January" "February" "March" "April" "May" "June"
# ;;    			         "July" "August" "September" "October" "November" "December"])
[[https://emacs.stackexchange.com/questions/50543/insert-date-using-a-calendar-where-other-language-rather-than-english-is-desir][Link 1]]
# ;;(let ((system-time-locale "en_GB.UTF-8")
# ;;      (time (org-read-date nil 'to-time nil "Date:  ")))
# ;;  (insert (format-time-string "(KW%W) (%A) %d. %B %Y" time)))(KW37) (poniedziałek) 12. września 2022
# ;; => (KW19) (Samstag) 18. Mai 2019
[[https://stackoverflow.com/questions/28913294/emacs-org-mode-language-of-time-stamps][Link 3]]
# ;; System locale to use for formatting time values.
# (setq system-time-locale "C")         ; Make sure that the weekdays in the
#                                       ; time stamps of your Org mode files and
#                                       ; in the agenda appear in English.


The best method I found working for my purposes is:
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(setq system-time-locale "C")         ; Force Emacs to use English timestamps
#+end_src
It makes Emacs use English language and not the system localization language
when inserting weekdays abreviations in org-mode timestamps and in org-agenda.

***** DONE Calendar
Inserting the date from the calendar. 
Here's the way how one can insert date in org-mode by hitting ~C-c .~
choosing the day and hitting ~RET~.

The above shortcuts are listed in ~Scroll~ menu item which is visible in menu bar,
when you're in Calendar buffer.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; Calendar ->
(defun calendar-insert-date ()
  "Capture the date at point, exit the Calendar, insert the date."
  (interactive)
  (seq-let (month day year) (save-match-data (calendar-cursor-to-date))
    (calendar-exit)
    (insert (format "%d-%02d-%02d" year month day))))
#+end_src
Warning! Here, instead of using:
#+begin_example
(define-key calendar-mode-map (kbd "RET") 'calendar-insert-date)
#+end_example
it's better to define the action as

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(eval-after-load "calendar"
  `(progn
     (define-key calendar-mode-map (kbd "RET") 'calendar-insert-date)))
;; <- Calendar
#+end_src

Otherwise, you may get ~calendar-mode-map is void~ error, 
if ~calendar-mode-map~ it's not loaded at the moment of executing the command ([[https://emacs.stackexchange.com/questions/3548/how-to-change-key-bindings-for-calendar-mode][Link]]).


Moving in calendar buffer is like follows:

| Move by  | Backward | Forward   |
|----------+----------+-----------|
| a day    | S-<left> | S-<right> |
| a week   | S-<up>   | S-<down>  |
| a month  | >        | <         |
| 3 months | M-v      | C-v       |
| a year   | 4 M-v    | 4 C-v     |
|----------+----------+-----------|


**** Easy moving between windows
It is managed by [[https://www.emacswiki.org/emacs/WindMove][WindMove package]] that is built-in in Emacs.
The default keybindings of this package is ~Shift arrow~, which sometimes
may be inconvenient (there are conflicts for example in org-mode, other 
packages that conflict with org are [[https://orgmode.org/manual/Conflicts.html][listed here]]).
That is why it's better to remap those keybindings to other 
combination (~Super-Key-<arrow>~ in the code below). 

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; windmove ->
;; Easy moving between windows
  
  ;; setting windmove-default-keybindings to super-<arrow> in order
  ;; to avoid org-mode conflicts
  (global-set-key (kbd "s-<left>")  'windmove-left)
  (global-set-key (kbd "s-<right>") 'windmove-right)
  (global-set-key (kbd "s-<up>")    'windmove-up)
  (global-set-key (kbd "s-<down>")  'windmove-down)
;; <- windmove
#+end_src

***** [DEPRECATED] Useful For Emacs < 27.1
(This section is deprecated. In Emacs 27.1 the package works ok without
the need of application of ~ignore-error-wrapper~ function.)

According to [[https://www.emacswiki.org/emacs/WindMove][package's wikipage]] there exist some problem with the package,
namely:
"When you run for instance windmove-left and there is no window on the left,
 windmove will throw exception (and if you have debug-on-error enabled) 
you will see Debugger complaining."

Proposed workaround requires ~cl~ package, which unfortunately is
[[https://github.com/kiwanami/emacs-epc/issues/35][deprecated in Emacs 27.1]] (The workaround worked in Emacs < 27).
With the use of 
[[https://emacs.stackexchange.com/questions/15189/alternative-to-lexical-let][this post]] and 
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Lexical-Binding.html][this part of emacs manual]] I sort of solved the problem and with the 
following code Emacs does not throw warnings or errors.

#+begin_src emacs-lisp 
;; windmove ->
;; Easy moving between windows
  (when (fboundp 'windmove-default-keybindings)
    (windmove-default-keybindings))
  
  (eval-when-compile (require 'cl))
  (setq lexical-binding t)
  
  (defun ignore-error-wrapper (fn)
    "Funtion return new function that ignore errors.
     The function wraps a function with `ignore-errors' macro."
    (lexical-let ((fn fn))
      (lambda ()
        (interactive)
        (ignore-errors
          (funcall fn)))))
  
  ;; setting windmove-default-keybindings to super-<arrow> in order
  ;; to avoid org-mode conflicts
  (global-set-key (kbd "s-<left>") (ignore-error-wrapper 'windmove-left))
  (global-set-key (kbd "s-<right>") (ignore-error-wrapper 'windmove-right))
  (global-set-key (kbd "s-<up>") (ignore-error-wrapper 'windmove-up))
  (global-set-key (kbd "s-<down>") (ignore-error-wrapper 'windmove-down))
;; <- windmove
#+end_src




**** Easy windows resize
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; Easy windows resize ->
  (define-key global-map (kbd "C-s-<left>") 'shrink-window-horizontally)
  (global-set-key        (kbd "C-s-<right>") 'enlarge-window-horizontally)
  (global-set-key        (kbd "C-s-<down>") 'shrink-window)
  (global-set-key        (kbd "C-s-<up>") 'enlarge-window)
;; <- Easy windows resize 
#+end_src


*** Completing 
ido/smex vs ivy/counsel/swiper vs helm 
**** ido-mode
# Temporarily deselected in order to test [[ivy-package]].

They say that ~ido~ is a [[https://www.masteringemacs.org/article/introduction-to-ido-mode][powerful package]] and you should have it enabled...
I'm not going to argue with that, yet I haven't studied much its capabilities.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
  ;; ido-mode ->
    (ido-mode 1)          
    (setq ido-enable-flex-matching t)
    (setq ido-everywhere t)  ; ido-mode for file searching
  ;; <- ido-mode
#+end_src

**** smex
# Temporarily deselected in order to test [[ivy-package]].

This package is installed because I was inspired by some post. 
Just for tests.
https://github.com/nonsequitur/smex/

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
  ;; smex ->
  (global-set-key (kbd "M-x") 'smex)
  (global-set-key (kbd "M-X") 'smex-major-mode-commands)
  ;; This is your old M-x.
  (global-set-key (kbd "C-c C-c M-x") 'execute-extended-command) 
  ;; <- smex
#+end_src

**** TODO Ivy (for testing) <<ivy-package>>
Furthermore, according to [[https://ruzkuku.com/emacs.d.html#org804158b][some other users]]
"Ivy is simpler (and faster) than Helm but more powerful than Ido".

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
  ;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; ;; *** Ivy
  ;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  ;; (setq ivy-wrap t)
  ;; (setq ivy-height 8)
  ;; (setq ivy-display-style 'fancy)
  ;; (setq ivy-use-virtual-buffers t)
  ;; (setq ivy-case-fold-search-default t)
  ;; (setq ivy-re-builders-alist '((t . ivy--regex-ignore-order)))
  ;; (setq enable-recursive-minibuffers t)
  ;; (ivy-mode t)
#+end_src





**** Abbreviations (abbrev-mode)
I've just discovered this mode and wanted to use it.
I'm not sure whether ~abbrev-mode~, ~yasnippet~ and ~company~
aren't substitute modes. [[https://emacs.stackexchange.com/questions/42556/best-pratice-advices-for-abbrev-vs-completion-vs-snippets][Well, in fact they partly are]].

- [[https://www.youtube.com/watch?v=AtdWuYImviw][Abbrev-mode movie tutorial]]
- [[https://www.youtube.com/watch?v=Holxu96YKrc&t=1s][Xah movie tutorial]]
- [[http://xahlee.info/emacs/emacs/emacs_abbrev_mode_tutorial.html][Xah page about abbrev]]
  
Emacs abbreviations are
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
  ;; abbrev-mode ->
    (setq-default abbrev-mode t)          
    (read-abbrev-file "~/.emacs.d/abbrev_defs")
    (setq save-abbrevs t)  
  ;; <- abbrev-mode
#+end_src

***** Useful commands
- C-x a - inverse-add-global-abbrev
- C-x a i l - inverse-add-global-abbrev
- C-x a i g - inverse-add-mode-abbrev
- unexpand-abbrev
- edit-abbrevs
- list-abbrevs
- kill-all-abbrevs
  i 

*** Autocomplete
~auto-complete~ vs ~company~

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;; *** Auto-completing
;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(add-hook 'after-init-hook 'global-company-mode)
#+end_src

**** Recently opened files
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; Recently opened files ->
  (recentf-mode 1)
  (setq recentf-max-menu-items 50)
  (setq recentf-max-saved-items 50)
  ;; in original emacs this binding is for "Find file read-only"
  (global-set-key "\C-x\ \C-r" 'recentf-open-files)
;; <- Recently opened files
#+end_src

*** Bibliography - citations
**** oc [org-citations]
***** Bibliography <<org-citations>>
# ____________________________________________________________________________78

In Org 9.6 we do not need explicitely load ~oc~ libraries.
Everything is covered in my post concerning bibliography and org-mode.

# #+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
  # ;; org citations
  # ;; (require 'oc)    ; probably not needed 
  # ;; (require 'oc-basic)
  # ;; (require 'oc-biblatex)
# #+end_src

Useful links:
- https://orgmode.org/manual/Citations.html
- https://kristofferbalintona.me/posts/202206141852/
- https://github.com/jkitchin/org-ref
- https://blog.tecosaur.com/tmio/2021-07-31-citations.html#fn.3
- https://emacs.stackexchange.com/questions/71817/how-to-export-bibliographies-with-org-mode
- https://www.reddit.com/r/emacs/comments/q4wa40/issues_with_new_orgcite_for_citations/
- https://nickgeorge.net/science/org-ref-setup/







**** citar (to check?)
     https://github.com/emacs-citar/citar

*** Org customization
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Org customization
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src

**** Org-agenda activation
 https://orgmode.org/manual/Activation.html#Activation

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; org-agenda activation
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+end_src

**** Org-special-block-extras
[[http://alhassy.com/org-special-block-extras/][Author's page]]

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; **** org-special-block-extras -> 
(add-hook #'org-mode-hook #'org-special-block-extras-mode)
;; <- **** org-special-block-extras 
#+end_src

**** Org-babel
To have org-babel enabled (execution of portions of code):

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 

;; enabling org-babel
(org-babel-do-load-languages
 'org-babel-load-languages '(
			     (C . t)
			     (matlab . t)
			     ;;(perl . t)
			     (octave . t)
			     (org . t)
			     (python . t)
			     (shell . t)
 			     ))
			     
;; no question about confirmation of evaluating babel code block
(setq org-confirm-babel-evaluate nil)

#+end_src

**** Tailoring org-mode to markdown export
When exporting to markdown I want to add some keywords in a special format to
the preamble of .md file.
[[https://emacs.stackexchange.com/questions/74505/how-can-i-add-specific-text-to-the-content-generated-by-org-mode-export-to-mark#74513][How to do that is descried here.]]


#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; **** org-to-markdown exporter customization  -> 

(defun org-export-md-format-front-matter ()
  (let* ((kv-alist (org-element-map (org-element-parse-buffer 'greater-element)
                       'keyword
                     (lambda (keyword)
                       (cons (intern (downcase (org-element-property :key keyword)))
                             (org-element-property :value keyword)))))
         (lines (mapcar (lambda (kw)
                          (let ((val (alist-get kw kv-alist)))
                            (format (pcase kw
                                      ('author "%s: %s")
                                      ((or 'tags 'title) "%s: '%s'")
                                      (_ "%s: %s"))
                                    (downcase (symbol-name kw))
                                    (pcase kw
                                      ('date (substring val 1 -1))
                                      (_ val)))))
                        '(author date tags title))))
    (concat "---\n" (concat (mapconcat #'identity lines "\n")) "\n---")))

(defun my/org-export-markdown-hook-function (backend)
    (if (eq backend 'md)
        (insert (org-export-md-format-front-matter) "\n")))

;; This hook should be added per file in my org posts. Unfortunately, so far I don't know
;; how to do this.
(add-hook 'org-export-before-processing-hook #'my/org-export-markdown-hook-function)

#+end_src

Besides, in order to have markdown exporter options in menu appearing after
~C-c C-e~ you need to add 
([[https://stackoverflow.com/questions/22988092/emacs-org-mode-export-markdown/22990257#22990257][Link 1]], [[https://emacs.stackexchange.com/questions/4279/exporting-from-org-mode-to-markdown][Link 2]]):

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 

(require 'ox-md nil t)

;; <- **** org-to-markdown exporter customization
#+end_src



**** Miscellaneous oneliners
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; alphabetical ordered lists
(setq org-list-allow-alphabetical t)
#+end_src

**** TODO Asynchronous babel sessions
ob-comint.el

**** TODO Default org to latex exporting command
     


*** TODO Flyspell (TODO: dive deeper into the package and its capabilities)
https://ruzkuku.com/emacs.d.html#org804158b
https://www.emacswiki.org/emacs/FlySpell

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Flyspell 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src


#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
(flyspell-mode t)

    (defun flyspell-on-for-buffer-type ()
      "Enable Flyspell appropriately for the major mode of the current buffer.  Uses `flyspell-prog-mode' for modes derived from `prog-mode', so only strings and comments get checked.  All other buffers get `flyspell-mode' to check all text.  If flyspell is already enabled, does nothing."
      (interactive)
      (if (not (symbol-value flyspell-mode)) ; if not already on
	(progn
	  (if (derived-mode-p 'prog-mode)
	    (progn
	      (message "Flyspell on (code)")
	      (flyspell-prog-mode))
	    ;; else
	    (progn
	      (message "Flyspell on (text)")
	      (flyspell-mode 1)))
	  ;; I tried putting (flyspell-buffer) here but it didn't seem to work
	  )))
    
    (defun flyspell-toggle ()
      "Turn Flyspell on if it is off, or off if it is on.  When turning on, it uses `flyspell-on-for-buffer-type' so code-vs-text is handled appropriately."
      (interactive)
      (if (symbol-value flyspell-mode)
	  (progn ; flyspell is on, turn it off
	    (message "Flyspell off")
	    (flyspell-mode -1))
	  ; else - flyspell is off, turn it on
	  (flyspell-on-for-buffer-type)))

 (global-set-key (kbd "C-c f") 'flyspell-toggle )

(defun fd-switch-dictionary()
      (interactive)
      (let* ((dic ispell-current-dictionary)
    	 (change (if (string= dic "polish") "english" "polish")))
        (ispell-change-dictionary change)
        (message "Dictionary switched from %s to %s" dic change)
        ))
    
      (global-set-key (kbd "<f8>")   'fd-switch-dictionary)
#+end_src

*** Flymake/Flycheck

https://www.masteringemacs.org/article/spotlight-flycheck-a-flymake-replacement

In Emacs 27.1 ~flymake~ is said to be competitive with ~flycheck~ again.
It is built-in in Emacs. As for now, I'm gonna use ~flymake~.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Flymake
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(flymake-mode t)
#+end_src

*** Bash completions
Bash has usually very good command completion facilities, which aren't accessible by default from Emacs (except by running ~M-x term~). This package integrates them into regular commands such as ~shell-command~ and ~shell~.

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Bash completions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(bash-completion-setup)
#+end_src

# *** YASnippet
# #+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
# ;; *** YASnippet
# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

# (yas-global-mode t) ; activate yasnippet
# (yas/initialize)
# #+end_src


*** General global shortcuts not restricted to specific package/mode
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; Useful global shortcuts (text operations)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(global-set-key (kbd "C-d") 'delete-forward-char)    ; Backspace/Insert remapping
(global-set-key (kbd "C-S-d") 'delete-backward-char) 
; (global-set-key (kbd "M-S-d") 'backward-kill-word)
(global-set-key (kbd "C-c C-e s") 'mark-end-of-sentence)

(global-set-key (kbd "C-C C-e C-w C-w") 'eww-list-bookmarks) ; Open eww bookmarks
(defun mynet ()  (interactive) (eww-list-bookmarks))
#+end_src

*** Load Emacs theme of your preference
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Emacs theme
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src


**** Modus themes by Protesilaos Stavrou <<modus-theme>>
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; **** Modus theme by Protesilaos Stavrou
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src
- [[https://protesilaos.com/codelog/2021-01-11-modus-themes-review-select-faint-colours/][Author's page]]
- [[https://www.youtube.com/watch?v=JJPokfFxyFo][Youtube's tutorial]]

~noconfirm~ flag needs to be added for two reasons.
First, without it we cannot run Emacs in batch mode from command line
(~emacs -batch -load ~/.emacs.d/init.el ...~). Second,... (I forgot the 
second reason).

# This is taken from modus manual. Do not tangle or export this code now.
#+begin_src emacs-lisp  :exports noen
;; (setq modus-themes-headings ; this is an alist: read the manual or its doc string
;;       '((1 . (overline background variable-pitch 1.3))
;;         (2 . (rainbow overline 1.1))
;;         (t . (semibold))) )
#+end_src


#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 

;; Add all your customizations prior to loading the themes
(setq modus-themes-italic-constructs t
      modus-themes-bold-constructs nil
      modus-themes-region '(bg-only no-extend))

;; Load the theme of your choice:
(load-theme 'modus-vivendi :noconfirm) ;; OR (load-theme 'modus-operandi)

(setq modus-themes-headings ; this is an alist: read the manual or its doc string
      '((1 . (rainbow overline background 1.4))
        (2 . (rainbow background 1.3))
	(3 . (rainbow bold 1.2))
        (t . (semilight 1.1))))

(setq modus-themes-scale-headings t)
(setq modus-themes-org-blocks 'tinted-background)
#+end_src

*** Manually downloaded packages

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Manually downloaded packages
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")

;; Set location for external packages.
(add-to-list 'load-path "~/.emacs.d/manual-download/")

;; doconce -> 
(load-file "~/.emacs.d/manual-download/.doconce-mode.el")

;; activating org-mode for doconce pub files:
;; https://github.com/doconce/publish/blob/master/doc/manual/publish-user-manual.pdf
(setq auto-mode-alist
      (append '(("\\.org$" . org-mode))
              '(("\\.pub$" . org-mode))
              auto-mode-alist))
;; <- doconce
#+end_src

**** Sunrise - Norton Commander-like file browser
There are few packages to emulate Norton Commander experience in Emacs.
I tested ~mc.el~, ~nc.el~ and ~sunrise.el~. From these three only 
the last one turned out to be useful (or to run without errors).

https://www.emacswiki.org/emacs/Sunrise_Commander_Tips#h5o-1

https://pragmaticemacs.wordpress.com/2015/10/29/double-dired-with-sunrise-commander/

https://enzuru.medium.com/sunrise-commander-an-orthodox-file-manager-for-emacs-2f92fd08ac9e

- buttons extension for sunrise

 https://www.emacswiki.org/emacs/sunrise-x-buttons.el

https://pragmaticemacs.wordpress.com/2015/10/29/double-dired-with-sunrise-commander/

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; sunrise
(add-to-list 'load-path "~/.emacs.d/manual-download/sunrise")
(require 'sunrise)
(require 'sunrise-buttons)
(require 'sunrise-modeline)
(add-to-list 'auto-mode-alist '("\\.srvm\\'" . sr-virtual-mode))
#+end_src


**** Buffer-move - swapping buffers easily
https://www.emacswiki.org/emacs/buffer-move.el

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; buffer-move - swap buffers easily
(require 'buffer-move)
#+end_src

Now you can use commands:
~buf-move-up~
~buf-move-down~
~buf-move-left~
~buf-move-right~

or you can define keybindings as package documentation recommends 
(I guess it'll be used too seldom to waste keybinding for that):

#+begin_src
;; (global-set-key (kbd "<C-S-up>")     'buf-move-up)
;; (global-set-key (kbd "<C-S-down>")   'buf-move-down)
;; (global-set-key (kbd "<C-S-left>")   'buf-move-left)
;; (global-set-key (kbd "<C-S-right>")  'buf-move-right)
#+end_src


**** Other packages
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;; [DEPRECATED] - use sunrise instead of this
;; midnight-commander emulation
;; (require 'mc)
#+end_src

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
;; org to ipython exporter
;;(use-package ox-ipynb
;  :load-path "~/.emacs.d/manual-download/ox-ipynb")
#+end_src


*** TODO The end
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** The ending
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src
**** Workgroups (should be executed at the end of init.el) <<workgroups2-and-sessions>>
https://tuhdo.github.io/emacs-tutor3.html

~workgroups2~ is a fine package for managing session. To enable it and 
set the filepath for keeping sessions (default is ~/.emacs_workgroups~)
 put this in your ~init.el~:
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
(workgroups-mode 1)    ; session manager for emacs
(setq wg-session-file "~/.emacs.d/.emacs_workgroups") ; 
#+end_src

And then you can use the following commands to manage sessions:

- To save window&buffer layout as a work group:
~M-x wg-create-workgroup~ or
~C-c z C-c~

- To open an existing work group:
~M-x wg-open-workgroup~ or 
~C-c z C-v~

- To delete an existing work group:
~M-x wg-kill-workgroup~ or
~C-c z C-k~

There is one problem with ~workgroups2~ packages. It does not like with 
~desktop-save-mode~. When ~workgroups2~ is enabled ~desktop-save-mode~ 
does not restore the windows layout from the previous Emacs session, which
sucks.
I decided to stick to ~workgroups2~ and supply the needed functionality 
with the use of only this package. I did it by adding hooks:

#+begin_src emacs-lisp 
(add-hook 'kill-emacs-hook (
                     lambda () (wg-create-workgroup "currentsession" )))

(setq inhibit-startup-message t)

(add-hook 'window-setup-hook (
                       lambda () (wg-open-workgroup "currentsession")))
#+end_src

The line ~(setq inhibit-startup-message t)~ is added in order to prevent
Emacs splash screen to appear in one of the restored ~"currentsession"~ frames.

There is one problem with the code above. When running Emacs in batch mode like
this:

~emacs -batch -Q -load ~/.emacs.d/init.el~

(I have such a line of code in the makefile of this blog)
it asks in the command line about saving the "currentsession". It sucks.
As a workaround we can put those hooks inside if statement, which checks
whether Emacs was run in batch mode or not.
How to write an if statements is [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Conditionals.html][here]].
In the code below I also use
[[https://emacs.stackexchange.com/questions/20603/how-to-know-if-emacs-is-running-in-batch-mode][~noninteractive~ variable]] which is true
if emacs is run in batch mode.

The code below somehow worked for a while. Then, out of a sudden it stopped.

#+begin_src emacs-lisp 
(if (not noninteractive)
    ( ; if Emacs is started in graphical environment
      (add-hook 'kill-emacs-hook (
                     lambda () (wg-create-workgroup "currentsession")))
      (setq inhibit-startup-message t)
      (add-hook 'window-setup-hook (
                       lambda () (wg-open-workgroup "currentsession")))
    )
   (
    ; if Emacs is run in batch mode - do not care about workgroups
   )
)
#+end_src

The problem was the lack of a special keyword ~progn~ as I found
[[https://stackoverflow.com/questions/912355/how-can-you-write-multiple-statements-in-elisp-if-statement][here]] ([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Sequencing.html][Part of the manual about it]]). All in all, now everything seems
to be ok with the following lines:

#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") 
  (if (not noninteractive)
      ( ; if Emacs is started in graphical environment
        progn
	(add-hook 'kill-emacs-hook (
		       lambda () (wg-create-workgroup "currentsession")))
	(setq inhibit-startup-message t)
	(add-hook 'window-setup-hook (
			 lambda () (wg-open-workgroup "currentsession")))
      )
     (
      ; if Emacs is run in batch mode - do not care about workgroups
     )
  )
#+end_src



**** Last lines
#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el") :exports none
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; *** Finishing touches
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#+end_src


**** [DEPRECATED] Restoring previous session
This section is deprecated in favour of [[workgroups2-and-sessions][~workgroups2 package~]].

This way of restoring session throws some warnings and needs additional
confirmations so I give it up. Simple ~(desktop-save-mode 1)~ which is 
included [[oneliners][in the beginning of ~init.el~]] works ok.

#+begin_src emacs-lisp 
;; Restore the "desktop" - do this as late as possible
(if first-time
    (progn
      ;(desktop-load-default)   ; this is for Emacs 20-21
      (desktop-read)))

;; Indicate that this file has been read at least once
(setq first-time nil)
#+end_src

**** [DEPRECATED] Open some useful files in the background
I don't use this part of ~init.el~ anymore. I can get the similar
functionality by using ~recentf~ package or prepare a session
with required files opened in it.

# #+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
#+begin_src emacs-lisp
  ;;; Always have several files opened at startup
  ;; hint: https://stackoverflow.com/a/19284395/4649238
  (find-file "~/.emacs.d/init.el")
  (find-file "~/.emacs.d/install-packages.el")
  (find-file "~/.emacs.d/useful-shortcuts.org")
#+end_src

What's more, the commands above cause an unwanted behaviour when
evaluating ~init.el~. The last file in the list is opened in an active buffer.
I'd like to have those files opened "in background".
I found ~find-file-noselect~ function have this functionality,
but first: it is [[https://emacs.stackexchange.com/questions/2868/whats-wrong-with-find-file-noselect][not recommended way]] of doing this thing;
second: it is not present in Emacs 27.1 anyway.



#+begin_src emacs-lisp :tangle (concat (org-entry-get nil "PRJ-DIR" t) "init.el")
  ;; All done
  (message "All done in init.el.")
#+end_src

** Dependencies of the presented Emacs configuration <<dependencies-section>>:
The list of external applications that this script is dependent on:
- git
- LaTeX distribution (for org to latex exporters)
  
