# ____________________________________________________________________________78

#+TITLE: Bibliography and org-mode
#+DESCRIPTION: 
#+AUTHOR: cissic
#+DATE: <2022-12-23 Fri>
#+TAGS: emacs org TODO
#+OPTIONS: toc:nil
#+OPTIONS: -:nil



* {{{title}}}
:PROPERTIES:
:PRJ-DIR: ./2022-12-23-bibtex-and-org/
:END:

** Problem
How to write in =org= and use bibliography files? 
New, simple and universal way of management of bibliography appeared quite recently in Emacs. It's described in the following links: 
[[https://orgmode.org/manual/Citations.html][org-man]], 
[[https://blog.tecosaur.com/tmio/2021-07-31-citations.html][author's blog]], 
[[https://emacs.stackexchange.com/questions/71817/how-to-export-bibliographies-with-org-mode][stackexchange post]]. 

There are some problems with it on my Debian Bullseye. Probably it's too new to work out of the box. It seems that it was introduced in =Org 9.6=, and =Org 9.6= it too new for Emacs from Bullseye repositories.

These problems were described in previous post and are mentioned 
[[https://github.com/syl20bnr/spacemacs/issues/15360][here]], 
[[https://www.reddit.com/r/emacs/comments/zd3l7p/org_mode_elpa_intall_invalid_function/][here]] and 
[[https://list.orgmode.org/87bkonzisl.fsf@gnu.org/T/#u][here]].

Since I don't have time to deal with all those troubles I decided to give up this apprach for now. I'm going to come back again when all those teething problems are solved in the next versions of org and emacs...

** Solution 
For now I decided to use some simple workaround. Assuming we have a bib file like this: 

#+begin_src org :tangle (concat (org-entry-get nil "PRJ-DIR" t) "biblio.bib")

 @article{a1,
   title = {Art 1},
   author = {Author, A.},
   year = {1997},
   month = jul,
   journal = {journal},
   volume = {20},
   number = {1},
   pages = {51--61},
 }

 @article{a2,
  title = {Art 2},
  author = {Author, B.},
  year = {1997},
  month = jul,
  journal = {journal},
  volume = {20},
  number = {1},
  pages = {51--61},
 }

#+end_src
we can attach it to org-mode document like this:

#+begin_src org :tangle (concat (org-entry-get nil "PRJ-DIR" t) "Ex1.org") :mkdirp yes

      #+TITLE: Some title
      #+AUTHOR: Some author
      #+LATEX_CLASS: article      
      #+BIBLIOGRAPHY: biblio.bib 

      * Chapter 1
      This is the text. \cite{a1}, \cite{a2}
      
      \bibliography{biblio}
      \bibliographystyle{plain}


      # Local Variables:
      # eval: (setq org-latex-pdf-process (list "latexmk -pdflatex='latex -shell-escape -interaction nonstopmode' -pdf -f  %f"))
      # End:
      
          

#+end_src
