# ____________________________________________________________________________78
#+TITLE: Hyphenation in MikTeX (UNRESOLVED)
#+DESCRIPTION: 
#+AUTHOR: cissic
#+DATE: <2022-11-16 Wed>
#+TAGS: latex miktex hyphenation
#+OPTIONS: toc:nil
#+OPTIONS: -:nil


* Workaround \label{Sec:workaround}
After unsuccessful attempts to make hyphenation rules working in MikTeX
I decided to use a workaround, which comes down to adding command
#+begin_example
\sloppy
#+end_example
in the preamble of the LaTeX document (~#+LATEX_HEADER:\sloppy~ in an .org file).


* Problem description

Basing on instructions presented on official MikTeX page I installed MikTeX

#+begin_example
echo "deb http://miktex.org/download/debian bullseye universe" | sudo tee /etc/apt/sources.list.d/miktex.list

sudo apt-get update
sudo apt-get install miktex
#+end_example

and then I configured it. However there exist some problem with language support. hyphenation patterns etc, which prevents from compiling the following MWE:

:PROPERTIES:
:PRJ-DIR: ./2022-11-16-MikTeX-Hyph-MWE/
:END:

#+begin_src latex :tangle (concat (org-entry-get nil "PRJ-DIR" t) "main.tex") :mkdirp yes
  \documentclass{article}  
  \usepackage{babel}
  \usepackage{polski}

  \clubpenalty = 10000
  \widowpenalty = 10000
  \sloppy

  \begin{document}
  To jest tekst w języku polskim.
  \end{document}

#+end_src

I tried to follow the hints from [[https://tex.stackexchange.com/questions/365804/how-to-fix-the-warning-no-hyphenation-patterns-were-preloaded-for-babel-the-l][here]], but with no success.

Finally I rebuilt the format by opening MikTeX Console and choosing

#+begin_example
Settings -> Formats -> (choose from a list) pdflatex 
-> (click) Build format
#+end_example

and managed to compile with ~\usepackage{polski}~ without an error, however
I still kept obtaining words that exceeded the text column.
In the end I decided to use a workaround presented in section \ref{Sec:workaround}.



 
# #+begin_example
# (add-to-list 'org-structure-template-alist '("m" . "src python :session :exports results :results output latex replace "))
# #+end_example

# to add an item in the menu appearing after ~C-c C-,~.

# ** Side note
# The information given [[https://kitchingroup.cheme.cmu.edu/blog/2014/01/26/Language-specific-default-headers-for-code-blocks-in-org-mode/][here]] must be outdated becasue emacs spits out some error/warnings when I add lines from this link in my ~init.el~.


