# ____________________________________________________________________________78

#+TITLE: How to open an org file with local variables without being prompt about them?
#+DESCRIPTION: 
#+AUTHOR: cissic
#+DATE: <2023-01-17 Tue>
#+TAGS: emacs org org-mode local-variables
#+OPTIONS: toc:nil
#+OPTIONS: -:nil


* TODO {{{title}}}
:PROPERTIES:
:PRJ-DIR: ./2023-01-17-local-vars-in-org/
:END:


** Problem description
While writing this "blog" I have some commands stored in each org-file
which correspond to a single post, that changes the behaviour
of the default org-mode markdown exporter in order to do some
specific stuff automatically (See the post about tailoring org mode
export from <2022-10-10 Mon>). (I believe there exist some smarter
way of achieving this functionality, than to add local-variables
to each org file, but I'm going to leave it alone until
I get some more knowledge and proficiency in emacs lisp.)

The drawback of this solution is that emacs asks about
activating local variables every time any of those
org-file posts is being opened in editor.

[[https://www.reddit.com/r/emacs/comments/6rtwmo/how_do_you_open_a_file_but_keep_it_in_the/][Here]] I found a clue how can this be avoided. It seems
I should use the variable ~enable-local-variables~ but only
in the context of the files in a specific directory (directory
where my org-file posts are stored). 

*** TODO Solution
I'd like to have ~enable-local-variables~ variable 



# Local Variables:
# eval: (add-hook 'org-export-before-processing-hook 
# 'my/org-export-markdown-hook-function nil t)
# End:
