#+TITLE: sudo password input in KDE for the script run in bash
#+DESCRIPTION: 
#+AUTHOR: cissic 
#+DATE: <2024-09-11 Wed>
#+TAGS: sudo password KDE 
#+OPTIONS: -:nil

* sudo password input in KDE for the script run in bash
:PROPERTIES:
:PRJ-DIR: ./2024-09-11-sudo-password-input-in-KDE-for-the-script-run-in-bash/
:END:


** Problem description
Sometimes you may want to trigger bash script with sudo command
from GUI (for example bash script triggered by some keybinding).
In this situation there appears a problem with passing sudo password.

You can always include the password in the bash script 
ausing =-S= switch 
#+begin_src shell
echo <password> | sudo -S <command>
#+end_src
or try to use some other methods mentioned
[[https://superuser.com/questions/67765/sudo-with-password-in-one-command-line][here]].
Of course the safety reasons require some more secure approach.

[[https://askubuntu.com/questions/314395/proper-way-to-let-user-enter-password-for-a-bash-script-using-only-the-gui-with][This thread]] may come in handy. With the use of =zenity=
or some other password asking program (=zenity= was already installed
in my debian distribution) simply create a file:

#+begin_src shell :tangle "~/binmb/myaskpass.sh" :mkdirp yes 
#!/bin/bash
zenity --password --title=Authentication
#+end_src

Then insert this line at the beginning of your script:
#+begin_src shell 
export SUDO_ASKPASS="/path/to/myaskpass.sh"
#+end_src
(NOTE: do use full path to the script, =~= for =/home/user/= directory
may not work)
and replace all occurences of sudo <command> with:

#+begin_src shell 
sudo -A <command>
#+end_src
