#+TITLE: Zero width space
#+DESCRIPTION: 
#+AUTHOR: cissic
#+DATE: <2024-01-11 Thu>
#+TAGS: org-mode markup zero-width-space
# #+OPTIONS: toc:nil
#+OPTIONS: -:nil


* TODO {{{title}}}
:PROPERTIES:
:PRJ-DIR: ./2024-01-10-zero-width-space/
:END:

** Problem description
[[https://orgmode.org/manual/Escape-Character.html][org-mode manual]]

Sometimes you may need to concatenate some word written with org-mode
markup syntax with the one written in plain text. Leeaving no space
between these two word leads to loosing emacs markup feature.
Consider the example:

   This word is *bold* ed, but you leave unwanted space between =bold= and =ed=. which
   is visible after export process.

   This word is not =bold=ed because you leave no space between two words in org-mode,
   and you loose org-mode syntax.

** Solutions:
*** Add =-= (minus sign) if applicable
It seems that adding minus sign does not intefere with org-mode syntax:

  This word is *bold*-ed, and another one is =monospace=-d

*** Use zero width space

You can insert so-called =zero width space= as it is
explained in https://orgmode.org/manual/Escape-Character.html.
You do it by typing
: C-x 8 <RET> zero width space <RET>
: C-x 8 <RET> 200B <RET>

With this character you can write for example
#+begin_example
[X[1,2]]
or
*bold*Xed
#+end_example
where ‘X’ denotes the zero width space character, resulting in:

[​[1,2]]
or
*bold*​ed

Bingo!

** WARNING!:
When using zero width space rememeber to add
=-interaction nonstopmode=
during pdflatex compilation. Otherwise you'll get an error.

If still obtaining an errors during latex compilation it may be
helpful to add to =#+LATEX_HEADER=.

#+begin_src latex 
\ifTUTeX
  \usepackage{fontspec}
\else
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc} % The default since 2018
  \DeclareUnicodeCharacter{200B}{{\hskip 0pt}}
\fi
#+end_src



* COMMENT Local Variables

# Local Variables:
# eval: (setq org-latex-pdf-process
#  '("pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -output-directory %o %f"
#    "pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -output-directory %o %f"
#    "pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -output-directory %o %f"))
# End:
 
